CREATE TABLE `LOTTO_HISTORY` (
  `BNUSNO` int(11) NOT NULL,
  `FIRSTWINAMNT` bigint(20) DEFAULT NULL,
  `TOTSELLAMNT` bigint(20) DEFAULT NULL,
  `DRWTNO1` int(11) NOT NULL,
  `DRWTNO2` int(11) NOT NULL,
  `DRWTNO3` int(11) NOT NULL,
  `DRWTNO4` int(11) NOT NULL,
  `DRWTNO5` int(11) NOT NULL,
  `DRWTNO6` int(11) NOT NULL,
  `DRWNODATE` date NOT NULL,
  `DRWNO` int(11) NOT NULL,
  `FIRSTPRZWNERCO` int(11) DEFAULT NULL,
  `CREATE_DATE` date NOT NULL,
  PRIMARY KEY (`DRWNO`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;