CREATE TABLE `LOTTO_HISTORY` (
  `BNUSNO` int(11) NOT NULL,
  `FIRSTWINAMNT` int(11) DEFAULT NULL,
  `TOTSELLAMNT` int(11) DEFAULT NULL,
  `DRWTNO1` int(11) NOT NULL,
  `DRWTNO2` int(11) NOT NULL,
  `DRWTNO3` int(11) NOT NULL,
  `DRWTNO4` int(11) NOT NULL,
  `DRWTNO5` int(11) NOT NULL,
  `DRWTNO6` int(11) NOT NULL,
  `DRWNODATE` int(11) NOT NULL,
  `DRWNO` int(11) NOT NULL,
  `FIRSTPRZWNERCO` int(11) DEFAULT NULL,
  `CREATE_DATE` date NOT NULL,
  PRIMARY KEY (`DRWNO`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;